name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "export PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token

      - name: Container login
        run: heroku container:login

      - name: Push Docker image to Heroku
        run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Docker image on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
