name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "export PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

      - name: Authenticate with Heroku
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login ${HEROKU_EMAIL}
            password ${HEROKU_API_KEY}
          machine git.heroku.com
            login ${HEROKU_EMAIL}
            password ${HEROKU_API_KEY}
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Container login
        run: heroku container:login

      - name: Push Docker image to Heroku
        run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Docker image on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
